# Generated by Django 4.1.1 on 2022-09-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
