# Generated by Django 4.1.1 on 2022-09-06 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0002_alter_itemdetail_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(7500.0)]),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='receipt_pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='org_api.status'),
        ),
    ]
