# Generated by Django 4.1.1 on 2022-09-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0003_alter_itemdetail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(null=True, upload_to='room_images)'),
        ),
    ]
