# Generated by Django 4.1.1 on 2022-09-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0004_alter_room_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(null=True, upload_to='room_images'),
        ),
    ]
