# Generated by Django 4.1.1 on 2022-09-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0005_alter_room_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(null=True, upload_to='item_images'),
        ),
    ]
