# Generated by Django 4.1.1 on 2022-09-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0006_alter_item_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetail',
            old_name='status_id',
            new_name='status',
        ),
    ]
