# Generated by Django 4.1.1 on 2022-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0007_rename_status_id_itemdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='receipt_pic',
            field=models.ImageField(null=True, upload_to='receipt_images'),
        ),
    ]
