# Generated by Django 4.1.1 on 2022-09-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0008_alter_itemdetail_receipt_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='serial_num',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
