# Generated by Django 4.1.1 on 2022-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0010_alter_itemdetail_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='receipt_pic',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_images'),
        ),
    ]
