# Generated by Django 4.1.1 on 2022-09-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0011_alter_itemdetail_receipt_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='purchased_from',
            field=models.CharField(blank=True, default=0, max_length=55, null=True),
        ),
    ]
