# Generated by Django 4.1.1 on 2022-09-18 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0012_alter_itemdetail_purchased_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(7500.0)]),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
