# Generated by Django 4.1.1 on 2022-09-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0015_alter_itemdetail_price_alter_itemdetail_receipt_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_item', to='org_api.item'),
        ),
    ]
