# Generated by Django 4.1.1 on 2022-09-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0017_alter_itemdetail_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetail',
            name='receipt_pic',
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_pic', models.ImageField(null=True, upload_to='receipt_images')),
                ('item_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='org_api.itemdetail')),
            ],
        ),
    ]
