# Generated by Django 4.1.1 on 2022-09-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_api', '0018_remove_itemdetail_receipt_pic_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='approved',
        ),
        migrations.AddField(
            model_name='organizer',
            name='approved_users',
            field=models.ManyToManyField(related_name='app_user', through='org_api.Family', to='org_api.organizer'),
        ),
    ]
